# Generated by Django 5.1.1 on 2024-10-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField(null=True)),
                ('location_id', models.IntegerField(null=True)),
                ('enemy_class', models.IntegerField(default=0)),
                ('is_it_enemy', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='enemy',
            name='enemy_attack1_cooldown',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='enemy',
            name='enemy_attack1_damage_max',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='enemy',
            name='enemy_attack1_damage_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='enemy',
            name='enemy_attack2_cooldown',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='enemy',
            name='enemy_attack2_damage_max',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='enemy',
            name='enemy_attack2_damage_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='enemy',
            name='enemy_class',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='enemy',
            name='health',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='id_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='trap_damage_max',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='location',
            name='trap_damage_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='damage_max',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='player',
            name='damage_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='health',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='player',
            name='player_attack1_cooldown',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='player_attack1_damage_max',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='player',
            name='player_attack1_damage_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='player_attack2_cooldown',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='player_attack2_damage_max',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='player',
            name='player_attack2_damage_min',
            field=models.IntegerField(default=1),
        ),
    ]
