# Generated by Django 5.1.1 on 2024-10-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quest', '0002_map_enemy_enemy_attack1_cooldown_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map_len',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_len', models.IntegerField(default=7)),
            ],
        ),
    ]
